name: StickStaffs
version: 1.5.3
main: me.bananentoast.stickstaffs.StickStaffs
api-version: 1.18
authors: [ Bananentoast ]
description: A collection of useless Stickstaffs
website: https://github.com/Bananentoaster

commands:
  staff:
